"""
Libra API v1 - Tool Use & Sandbox Execution Endpoints

Provides endpoints for discovering available tools, inspecting their schemas,
and executing tools safely within the isolated sandbox environment.
"""

from __future__ import annotations

from typing import Any
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from packages.tools import (
    ParsedToolCall,
    ToolCallParser,
    ToolResult,
    get_tool_registry,
)

router = APIRouter()


class ToolInfo(BaseModel):
    """Metadata and schema for an available tool."""

    name: str
    description: str
    schema_def: dict[str, Any] = Field(..., alias="schema")


class ExecuteToolRequest(BaseModel):
    """Request payload to execute a registered tool."""

    name: str = Field(..., description="Name of the tool to execute")
    arguments: dict[str, Any] = Field(
        default_factory=dict, description="Arguments dictionary matching tool schema"
    )


class ParseToolCallRequest(BaseModel):
    """Request to parse tool calls from raw text output."""

    text: str = Field(..., description="Raw text generated by an LLM containing potential tool calls")


@router.get("", response_model=list[ToolInfo], summary="List all available tools and schemas")
async def list_tools() -> list[ToolInfo]:
    """Retrieve catalog of registered tools and their OpenAI-compatible schemas."""
    registry = get_tool_registry()
    tools = registry.list_tools()
    return [
        ToolInfo(
            name=t.name,
            description=t.description,
            schema=t.to_openai_schema(),
        )
        for t in tools
    ]


@router.get("/schemas", response_model=list[dict[str, Any]], summary="Get raw OpenAI function calling schemas")
async def get_schemas() -> list[dict[str, Any]]:
    """Retrieve raw OpenAI function calling schemas for model prompt formatting."""
    registry = get_tool_registry()
    return registry.get_schemas()


@router.post("/execute", response_model=ToolResult, summary="Execute a registered tool")
async def execute_tool(request: ExecuteToolRequest) -> ToolResult:
    """Execute a registered tool synchronously or asynchronously with sandboxed isolation."""
    registry = get_tool_registry()
    tool = registry.get(request.name)
    if not tool:
        raise HTTPException(
            status_code=404,
            detail=f"Tool '{request.name}' not found. Available: {registry.get_tool_names()}",
        )

    result = await registry.execute_tool_async(request.name, request.arguments)
    return result


@router.post("/parse", response_model=list[ParsedToolCall], summary="Parse tool calls from model output")
async def parse_tool_calls(request: ParseToolCallRequest) -> list[ParsedToolCall]:
    """Extract structured tool calls from raw model text (XML or JSON blocks)."""
    return ToolCallParser.parse(request.text)
