"""
Libra Agents Package - Inter-Agent Message Bus & Shared Blackboard

Provides the communication backbone and shared state container for
multi-agent collaborative ensembles and role-specialized agent teams.
"""

from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AgentRole(str, Enum):
    """Specialized personas within an autonomous collaborative team."""

    COORDINATOR = "coordinator"
    ARCHITECT = "architect"
    CODER = "coder"
    REVIEWER = "reviewer"
    TESTER = "tester"


class MessageType(str, Enum):
    """Semantic intent of an inter-agent message."""

    TASK = "task"
    SPECIFICATION = "specification"
    CODE_PROPOSAL = "code_proposal"
    CRITIQUE = "critique"
    TEST_RESULTS = "test_results"
    CONSENSUS_APPROVAL = "consensus_approval"
    FINAL_DELIVERY = "final_delivery"


class AgentMessage(BaseModel):
    """Structured communication packet passed between agents."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8], description="Unique message ID")
    sender_name: str = Field(..., description="Name of the emitting agent")
    sender_role: AgentRole = Field(..., description="Role of the emitting agent")
    recipient: str = Field("broadcast", description="Target recipient or 'broadcast'")
    message_type: MessageType = Field(..., description="Semantic purpose of the message")
    content: str = Field(..., description="Text payload or reasoning")
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Structured artifacts, code, or metrics"
    )
    timestamp: float = Field(default_factory=time.time, description="Unix timestamp of emission")


class SharedBlackboard(BaseModel):
    """
    Central shared state repository (Blackboard Pattern) accessible by all team agents.
    Tracks problem specification, candidate code, reviews, test assertions, and dialogue.
    """

    task: str = Field(..., description="Original user task prompt")
    specification: str = Field("", description="Architectural specification and requirements")
    candidate_code: str = Field("", description="Current active candidate Python code")
    test_assertions: str = Field("", description="Unit test assertions generated by the Tester")
    review_notes: str = Field("", description="Feedback and critique from the Reviewer")
    is_approved_by_reviewer: bool = Field(
        False, description="Whether Reviewer approved the candidate code"
    )
    test_output: str = Field("", description="Stdout or error trace from sandbox test execution")
    tests_passed: bool = Field(False, description="Whether sandbox unit test assertions succeeded")
    messages: list[AgentMessage] = Field(
        default_factory=list, description="Chronological log of messages"
    )
    artifacts: dict[str, Any] = Field(
        default_factory=dict, description="Arbitrary auxiliary artifacts"
    )

    def post_message(self, message: AgentMessage) -> None:
        """Appends a new message to the shared dialogue trace."""
        self.messages.append(message)

    def get_messages_for(self, agent_name: str, role: AgentRole) -> list[AgentMessage]:
        """Retrieves messages targeted to this agent or broadcast to all."""
        return [
            m for m in self.messages if m.recipient in ("broadcast", "all", agent_name, role.value)
        ]

    def format_dialogue_history(self, limit: int = 10) -> str:
        """Formats recent dialogue history for injection into prompt context."""
        recent = self.messages[-limit:] if limit > 0 else self.messages
        lines = []
        for m in recent:
            lines.append(
                f"[{m.sender_name} ({m.sender_role.value.upper()}) -> {m.recipient}]:\n{m.content}\n"
            )
        return "\n".join(lines).strip()
