"""
Phase 19 Interactive Demo: Program-Aided Language Models (PAL) & Test-Driven Auto-Debugging

Demonstrates:
1. PAL mathematical reasoning: Solving combinatorics accurately via sandboxed Python execution.
2. Auto-Debugger in action: Diagnosing an off-by-one bug and repairing it through reflection.
"""

import asyncio
import os
import sys
import time

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from packages.agents import (
    AutoDebugger,
    PALAgent,
    format_code_with_lines,
)
from packages.providers.base import BaseProvider, ModelMetadata
from packages.providers.router import ProviderRouter
from packages.tools.sandbox import SafePythonSandbox


class DemoScriptedProvider(BaseProvider):
    """Provides realistic scripted responses for the demonstration."""

    def __init__(self) -> None:
        self.call_count = 0

    @property
    def name(self) -> str:
        return "demo-provider"

    async def list_models(self) -> list[ModelMetadata]:
        return []

    async def chat(self, messages, model=None, **kwargs):
        self.call_count += 1
        user_msg = messages[-1]["content"]

        if "committee of 5" in user_msg or "chosen from 12" in user_msg:
            # PAL Response
            return {
                "choices": [
                    {
                        "message": {
                            "content": (
                                "To calculate the number of combinations of 5 from 12 (12 C 5), we use Python's math module:\n\n"
                                "```python\n"
                                "import math\n\n"
                                "def solution():\n"
                                "    n = 12\n"
                                "    k = 5\n"
                                "    return math.comb(n, k)\n"
                                "```"
                            )
                        }
                    }
                ]
            }
        else:
            # Auto-Debugger repair response
            return {
                "choices": [
                    {
                        "message": {
                            "content": (
                                "### Diagnostic Analysis:\n"
                                "The original code attempted to access `items[len(items)]` on line 2.\n"
                                "In Python, lists are 0-indexed with valid indices from 0 to `len(items) - 1`.\n"
                                "Accessing index `len(items)` raises an `IndexError: list index out of range`.\n\n"
                                "### Repair:\n"
                                "We can safely retrieve the last item using negative indexing `items[-1]`.\n\n"
                                "```python\n"
                                "def get_last_element(items: list):\n"
                                "    if not items:\n"
                                "        return None\n"
                                "    return items[-1]\n"
                                "```"
                            )
                        }
                    }
                ]
            }

    async def stream(self, messages, model=None, **kwargs):
        yield ""

    async def health(self):
        return {"status": "healthy"}

    async def embeddings(self, texts, model=None):
        return [[0.0] * 16]

    def capabilities(self):
        return {"supports_text": True}


async def main():
    print("=" * 70)
    print(" Project Libra — Phase 19: PAL & Test-Driven Auto-Debugging Demo")
    print("=" * 70)

    router = ProviderRouter()
    provider = DemoScriptedProvider()
    router._providers["demo-provider"] = provider
    sandbox = SafePythonSandbox(default_timeout=5.0)

    # -------------------------------------------------------------------------
    # Part 1: Program-Aided Language Model (PAL)
    # -------------------------------------------------------------------------
    print("\n--- Part 1: Program-Aided Language Model (PAL) ---")
    pal_prompt = "In how many ways can a committee of 5 people be chosen from 12 candidates?"
    print(f"User Inquiry: {pal_prompt}")

    pal_agent = PALAgent(
        model_id="demo-provider",
        provider_name="demo-provider",
        router=router,
        sandbox=sandbox,
    )

    t0 = time.perf_counter()
    pal_traj = await pal_agent.run(pal_prompt)
    elapsed = (time.perf_counter() - t0) * 1000.0

    print("\n[PAL Step 1] Code Generated by LLM:")
    print(pal_traj.steps[0].action_input.get("code"))
    print("\n[PAL Step 2] SafePythonSandbox Execution:")
    print(f"Observation: {pal_traj.steps[1].observation}")
    print(f"\nFinal Deterministic Answer: {pal_traj.final_answer}")
    print(f"Duration: {elapsed:.2f} ms | Status: {pal_traj.status.value.upper()}")

    # -------------------------------------------------------------------------
    # Part 2: Test-Driven Auto-Debugging Loop
    # -------------------------------------------------------------------------
    print("\n" + "-" * 70)
    print("--- Part 2: Test-Driven Auto-Debugging (Self-Correction Loop) ---")
    print("-" * 70)

    broken_code = (
        "def get_last_element(items: list):\n"
        "    return items[len(items)]\n"  # Off-by-one bug!
    )
    assertions = (
        "assert get_last_element([10, 20, 30]) == 30\n"
        "assert get_last_element(['alpha', 'beta']) == 'beta'\n"
        "assert get_last_element([]) is None"
    )

    print("\n[Initial Candidate Code with Bug]:")
    print(format_code_with_lines(broken_code))
    print(f"\n[Test Assertions to Satisfy]:\n{assertions}")

    debugger = AutoDebugger(
        model_id="demo-provider",
        provider_name="demo-provider",
        router=router,
        sandbox=sandbox,
    )

    t0 = time.perf_counter()
    debug_traj = await debugger.debug(
        task_description="Retrieve the last element of a list, or None if empty.",
        initial_code=broken_code,
        assertions=assertions,
        max_iterations=3,
    )
    elapsed = (time.perf_counter() - t0) * 1000.0

    print(f"\n[Debugging Iteration Trace ({debug_traj.total_attempts} attempt(s))]:")
    for it in debug_traj.iterations:
        print(f"\n  Attempt {it.iteration}:")
        print(f"    Success: {it.success}")
        if it.error:
            print(f"    Error Caught: {it.error}")
        if it.reflection:
            print(f"    Diagnostic Reflection:\n    {it.reflection}")

    print("\n[Final Verified Code]:")
    print(debug_traj.final_code)
    print(f"\nSuccess: {debug_traj.success} | Total Duration: {elapsed:.2f} ms")
    print("=" * 70)


if __name__ == "__main__":
    asyncio.run(main())
